#!/bin/sh

case "$1" in
install ) 
  echo "installing"
  # go build hello
  # nope.
  # build apparently compiles and put the bin in current dir. 
  # install puts the bin in the proper $GOPATH/bin dir. 
  go install musicdb
  echo "installed"
  ;;
read) 
  $GOPATH/bin/musicdb read /home/usr/music
  ;;
serve)
  $GOPATH/bin/musicdb serve
  ;;
*) 
  echo "try install or run. Or even brun"
  ;;
esac
